/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamIngestRouteImport } from './routes/api/stream/ingest'
import { Route as ApiSoundcloudStreamRouteImport } from './routes/api/soundcloud/stream'
import { Route as ApiSoundcloudSearchRouteImport } from './routes/api/soundcloud/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamIngestRoute = ApiStreamIngestRouteImport.update({
  id: '/api/stream/ingest',
  path: '/api/stream/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundcloudStreamRoute = ApiSoundcloudStreamRouteImport.update({
  id: '/api/soundcloud/stream',
  path: '/api/soundcloud/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundcloudSearchRoute = ApiSoundcloudSearchRouteImport.update({
  id: '/api/soundcloud/search',
  path: '/api/soundcloud/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/soundcloud/search': typeof ApiSoundcloudSearchRoute
  '/api/soundcloud/stream': typeof ApiSoundcloudStreamRoute
  '/api/stream/ingest': typeof ApiStreamIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/soundcloud/search': typeof ApiSoundcloudSearchRoute
  '/api/soundcloud/stream': typeof ApiSoundcloudStreamRoute
  '/api/stream/ingest': typeof ApiStreamIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/soundcloud/search': typeof ApiSoundcloudSearchRoute
  '/api/soundcloud/stream': typeof ApiSoundcloudStreamRoute
  '/api/stream/ingest': typeof ApiStreamIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/soundcloud/search'
    | '/api/soundcloud/stream'
    | '/api/stream/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/soundcloud/search'
    | '/api/soundcloud/stream'
    | '/api/stream/ingest'
  id:
    | '__root__'
    | '/'
    | '/api/soundcloud/search'
    | '/api/soundcloud/stream'
    | '/api/stream/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSoundcloudSearchRoute: typeof ApiSoundcloudSearchRoute
  ApiSoundcloudStreamRoute: typeof ApiSoundcloudStreamRoute
  ApiStreamIngestRoute: typeof ApiStreamIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/ingest': {
      id: '/api/stream/ingest'
      path: '/api/stream/ingest'
      fullPath: '/api/stream/ingest'
      preLoaderRoute: typeof ApiStreamIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundcloud/stream': {
      id: '/api/soundcloud/stream'
      path: '/api/soundcloud/stream'
      fullPath: '/api/soundcloud/stream'
      preLoaderRoute: typeof ApiSoundcloudStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundcloud/search': {
      id: '/api/soundcloud/search'
      path: '/api/soundcloud/search'
      fullPath: '/api/soundcloud/search'
      preLoaderRoute: typeof ApiSoundcloudSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSoundcloudSearchRoute: ApiSoundcloudSearchRoute,
  ApiSoundcloudStreamRoute: ApiSoundcloudStreamRoute,
  ApiStreamIngestRoute: ApiStreamIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
